# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
symbol = "âœ" # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
style = "bold blue"
[aws.region_aliases]
eu-west-2 = "LDN"

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ï¿½"
diverged = "ğŸ˜µ"
enabled = true
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged.style = "green"
staged.value = "++"
staged_count.enabled = true
staged_count.style = "green"
stashed = "ï¿½"
untracked = "ğŸ¤·â€"
